spring.application.name=e-commerce-microservices


spring.security.user.name=user
spring.security.user.password=12345

# Mongo DB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Customer_data
spring.data.mongodb.auto-index-creation=true

# Postgress configuration