spring.application.name=e-commerce-microservices

server.port=8080

# Mongo DB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Customer_data
spring.data.mongodb.auto-index-creation=true

# Postgress configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/CustomerData
spring.datasource.username=postgres
spring.datasource.password=rootsinside

#This line automatically creates tables if not already present 
spring.jpa.hibernate.ddl-auto=update

# .env file settings 
spring.config.import=optional:file:.env[.properties]

# Mail settings 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true