spring.application.name=e-commerce-microservices

server.port=8081
#Springboot security configuration
spring.security.user.name=user
spring.security.user.password=12345

# Mongo DB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Customer_data
spring.data.mongodb.auto-index-creation=true

# Postgress configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/CustomerData
spring.datasource.username=postgres
spring.datasource.password=rootsinside
#This line automatically creates tables if not already present 
spring.jpa.hibernate.ddl-auto=update